<? 
$erman_address="http://dslab.utdallas.edu/~ehsann/sharedride/";
$phpmailer_path="lib/PHPMailer_5.2.0";
$email_enabled=1;
$db_username="ehsansr";
$db_password="qrdKsbWY4Psj6fXK";
$db_host="dslabcomp";
$db_database="ehsansr";
?>
